In [11]:
from pathlib import Path
from typing import Dict, Tuple

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MaxAbsScaler

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 2000)
pd.set_option('display.expand_frame_repr', False)
pd.set_option("display.max_colwidth", None)  # or a large number like 2000

In [6]:
# Option 1: add src to sys.path, then import module name
import sys
sys.path.append(str(Path("../src").resolve()))
from features import DenseFeatureTransformer, add_clean_columns
from train import load_dataset

In [ ]:
df_sms = load_dataset("data/raw/spam.csv")
df_sms.head()

                                                text target
0  Go until jurong point, crazy.. Available only ...    ham
1                      Ok lar... Joking wif u oni...    ham
2  Free entry in 2 a wkly comp to win FA Cup fina...   spam
3  U dun say so early hor... U c already then say...    ham
4  Nah I don't think he goes to usf, he lives aro...    ham

In [12]:
model_df = add_clean_columns(df_sms, text_col="text")
model_df.head(20)

                                                                                                                                                                                                    text target                                                                                                                                                                                                 clean                                                                                                                                                                                              clean_ph
0                                                                                        Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...    ham                                                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
1                                                                                                                                                                          Ok lar... Joking wif u oni...    ham                                                                                                                                                                         Ok lar... Joking wif u oni...                                                                                                                                                                         Ok lar... Joking wif u oni...
2                                            Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's   spam                                        Free entry in 2 a wkly comp to win FA Cup final tkts 21 st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075 over 18's                               Free entry in <NUM> a wkly comp to win FA Cup final tkts <NUM> st May <NUM> . Text FA to <NUM> to receive entry question(std txt rate)T&C's apply <PHONE> over <NUM> 's
3                                                                                                                                                      U dun say so early hor... U c already then say...    ham                                                                                                                                                     U dun say so early hor... U c already then say...                                                                                                                                                     U dun say so early hor... U c already then say...
4                                                                                                                                          Nah I don't think he goes to usf, he lives around here though    ham                                                                                                                                         Nah I don't think he goes to usf, he lives around here though                                                                                                                                         Nah I don't think he goes to usf, he lives around here though
5                                                   FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv   spam                                                   FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv                                             FreeMsg Hey there darling it's been <NUM> week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, <MONEY> to rcv
6                                                                                                                          Even my brother is not like to speak with me. They treat me like aids patent.    ham                                                                                                                         Even my brother is not like to speak with me. They treat me like aids patent.                                                                                                                         Even my brother is not like to speak with me. They treat me like aids patent.
7                                       As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune    ham                                      As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune                                 As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press * <NUM> to copy your friends Callertune
8                                         WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.   spam                                        WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL 341. Valid 12 hours only.                                  WINNER!! As a valued network customer you have been selected to receivea <MONEY> prize reward! To claim call <PHONE> . Claim code KL <NUM> . Valid <NUM> hours only.
9                                             Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030   spam                                            Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030                                             Had your mobile <NUM> months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on <PHONE>
10                                                                                         I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.    ham                                                                                         I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.                                                                                         I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.
11                                                              SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info   spam                                                           SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH 11 and send to 87575. Cost 150 p/day, 6 days, 16+ TsandCs apply Reply HL 4 info                                        SIX chances to win CASH! From <NUM> to <NUM> pounds txt> CSH <NUM> and send to <NUM> . Cost <NUM> p/day, <NUM> days, <NUM> + TsandCs apply Reply HL <NUM> info
12                                          URGENT! You have won a 1 week FREE membership in our å£100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18   spam                                     URGENT! You have won a 1 week FREE membership in our £100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403 LDNW 1 A 7 RW 18                             URGENT! You have won a <NUM> week FREE membership in our <MONEY> Prize Jackpot! Txt the word: CLAIM to No: <NUM> T&C <URL> LCCLTD POBOX <NUM> LDNW <NUM> A <NUM> RW <NUM>
13  I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.    ham  I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.  I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.
14                                                                                                                                                                   I HAVE A DATE ON SUNDAY WITH WILL!!    ham                                                                                                                                                                   I HAVE A DATE ON SUNDAY WITH WILL!!                                                                                                                                                                   I HAVE A DATE ON SUNDAY WITH WILL!!
15                                                 XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL   spam                                                 XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL                                                       XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> <URL> xxxmobilemovieclub.com?n=QJKGIGHJJGCBL
16                                                                                                                                                                            Oh k...i'm watching here:)    ham                                                                                                                                                                            Oh k...i'm watching here:)                                                                                                                                                                            Oh k...i'm watching here:)
17                                                                                                                     Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.    ham                                                                                                                     Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.                                                                                                                 Eh u remember how <NUM> spell his name... Yes i did. He v naughty make until i v wet.
18                                                                                                                                            Fine if thatåÕs the way u feel. ThatåÕs the way its gota b    ham                                                                                                                                            Fine if thatåÕs the way u feel. ThatåÕs the way its gota b                                                                                                                                            Fine if thatåÕs the way u feel. ThatåÕs the way its gota b
19                                          England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/Ì¼1.20 POBOXox36504W45WQ 16+   spam                                      England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4 txt/£1.20 POBOXox 36504 W 45 WQ 16+                        England v Macedonia - dont miss the goals/team news. Txt ur national team to <NUM> eg ENGLAND to <NUM> Try:WALES, SCOTLAND <NUM> txt/ <MONEY> POBOXox <NUM> W <NUM> WQ <NUM> +